# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'tvm' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tvm
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crash'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Database'
  pod 'React', :path => '../node_modules/react-native'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'CxxBridge',
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket']

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
        
        if target.name == "yoga"
            target.remove_from_project
        end
    end
end
