export default {
  LOGINLOGO: require('./assets/img/tvm-logo.png'),
  LOGINBG: require('./assets/img/login-bg.png'),
  TOGGLEOFF: require('./assets/img/toggleoff.png'),
  TOGGLEON: require('./assets/img/toggleon.png'),
  STORYFEED: require('./assets/img/storyfeed.png'),
  LIVEICON: require('./assets/img/live.png'),
  SEARCHICON: require('./assets/img/search.png'),
  FEATUREDVIDEOS: require('./assets/img/featuredvideos.png'),
  MYSTORY: require('./assets/img/mystory.png'),
  TVMI: require('./assets/img/tvmi.png'),
  MENU: require('./assets/img/menu-icon.png'),
  ACTIVE_MENU: require('./assets/img/menu-icon-active.png'),
  BULLETIN_PLAY: require('./assets/img/news-bulletin.png'),
  STORY_PLAY: require('./assets/img/video-icon.png'),
  RADIO_PLAY: require('./assets/img/radju-playbutton.png'),
  PLAY: require('./assets/img/play.png'),
  RELATED_STORIES: require('./assets/img/storyfeed-pic1.png'),
  LIVE_PIC:require('./assets/img/storyfeed-pic1.png'),
  MENUICONACTIVE: require('./assets/img/menu_icon_active.png'),
  WALKTHROUGHBG: require('./assets/img/walkthroughbg.png'),
  WALKTHROUGHBG1: require('./assets/img/walkthroughbg1.png'),
  PAUSE:require('./assets/img/pausebutton.png'),
  SHARE_ICON:require('./assets/img/share-icon.png'),
  SAVE_ICON:require('./assets/img/saved.png'),
  UNSAVE_ICON:require('./assets/img/unsaved.png'),
  REMOVE_SAVE_ICON:require('./assets/img/remove-save.png'),
  NONSTOP:require('./assets/img/clock.png')
};
